version: "3.7"
services:
  elasticsearch-server:
    image: elasticsearch:8.5.3
    container_name: elasticsearch-server
    hostname: elasticsearch-server
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - bootstrap.memory_lock=true
      - cluster.name=elasticsearch-server
      - cluster.routing.allocation.disk.threshold_enabled=false
      # - xpack.security.http.ssl.enabled=false
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      # - "9300:9300"
    extra_hosts:
      - "hornsup:${HOST_IP}"
    depends_on:
      - logstash-server
  kibana-server:
    image: kibana:8.5.3
    container_name: kibana-server
    hostname: kibana-server
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-server
    extra_hosts:
      - "hornsup:${HOST_IP}"
      - "elasticsearch:${HOST_IP}"
  logstash-server:
    image: logstash:8.5.3
    container_name: logstash-server
    hostname: logstash-server
    environment:
      # - ELASTIC_USERNAME=elastic
      # - ELASTIC_PASSWORD=DkIedPPSCb
      - ELASTIC_PASSWORD=monday1
      - monitoring.elasticsearch.hosts=http://hornsup:9200
      - XPACK_MONITORING_ENABLED=false
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=true
    ports:
      - "9600:9600"
      - "4560:4560"
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
    extra_hosts:
      - "hornsup:${HOST_IP}"
      - "elasticsearch:${HOST_IP}"
volumes:
  elasticsearch-volume:
    name: elasticsearch-volume
    driver: local
