#!/bin/sh
exec tail -n +3 "$0"

# installed in bedroom on arch
menuentry "CentOS-7 5.0.2-1" {
  set root=(hd2,4)
  linux /boot/vmlinuz-5.0.2-1.el7.elrepo.x86_64 root=UUID=7555bb30-68c4-45f6-a24f-f4c4e4f91c26 rw quiet
  initrd /boot/initramfs-5.0.2-1.el7.elrepo.x86_64.img
}

menuentry "Windows 10" {
  set root=(hd2,1)
  chainloader +1
}

# installed in another system
menuentry "Mint 19.3" {
  set root=(hd0,1)
  linux /boot/vmlinuz-4.15.0-20-generic root=UUID=ffb5a152-1ca8-47a2-8629-443b59d81b41 ro quiet splash
  initrd /boot/initrd.img-4.15.0-20-generic
}

# to get UUID
# sudo blkid
menuentry "Arch Linux" {
  set root=(hd1,gpt6)
  linux /vmlinuz-linux root=/dev/nvme1n1p6
  initrd /initramfs-linux.img
}
