version: "3.7"
services:
  nginx-inject-js:
    build: .
    image: nginx-inject-js
    container_name: nginx-inject-js
    hostname: nginx-inject-js
    extra_hosts:
      - "hornsup:192.168.10.10"
    ports:
      - "443:443"
