version: "3.7"
services:
  nginx-server-macvlan:
    build: .
    # extra_hosts:
      # - "hornsup:192.168.10.10"
    container_name: nginx-server-macvlan
    ports:
      - "443:443"
    expose:
      - "443"
    restart: always
    network:
      - "macvlan-net"
