version: "3.7"
services:
  grafana-server:
    image: grafana/grafana:7.4.0
    user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: grafana-server
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=henninb
      - GF_SECURITY_ADMIN_PASSWORD=monday1
      - GF_HOST=localhost
      - GF_USER=henninb
      - GF_PASS=monday1
