version: "3.7"
services:
  nginx-reverse-proxy:
    build: .
    container_name: nginx-reverse-proxy
    extra_hosts:
      - "hornsup:192.168.10.10"
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
      - "3006:3006"
      - "3007:3007"
      - "3008:3008"
    expose:
      - "3001"
      - "3002"
      - "3003"
      - "3004"
      - "3006"
      - "3007"
      - "3008"
