version: "3.7"
services:
  varnish-server:
    image: varnish
    container_name: varnish-server
    ports:
      - "8484:80"
    expose:
      - "8484"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
  nginx-server:
    image: nginx
    container_name: nginx-server
    ports:
      - "80:80"
    expose:
      - "80"
