version: "3.7"
services:
  elasticsearch-server:
    container_name: elasticsearch-server
    hostname: elasticsearch-server
    image: elasticsearch:8.5.3
    environment:
      # - node.name=elasticsearch-server
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - bootstrap.memory_lock=true
      - cluster.name=elasticsearch-server
      - cluster.routing.allocation.disk.threshold_enabled=false
      # - xpack.security.http.ssl.enabled=false
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 65536
    #     hard: 65536
    # cap_add:
    #   - IPC_LOCK
    ports:
       - 9200:9200
    #   - 9300:9300
    # volumes:
    #   - data-elasticsearch:/usr/share/elasticsearch/data # mount data volume
    networks:
      - elasticsearch-network
  kibana-server:
    container_name: kibana-server
    hostname: kibana-server
    image: kibana:8.5.3
    environment:
      # - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch-server:9200
      # - ELASTICSEARCH_URL=http://elasticsearch-server:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-server
    networks:
      - elasticsearch-network
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.5.3
  #   volumes:
  #     - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
  #     - ./pipeline:/usr/share/logstash/pipeline:ro,Z
  #   environment:
  #     LS_JAVA_OPTS: -Xms256m -Xmx256m
  #   ports:
  #     - "5044:5044"
  #     - "50000:50000/tcp"
  #     - "50000:50000/udp"
  #     - "9600:9600"
    # networks:
      # - elasticsearch-network
volumes:
  data-elasticsearch:
    driver: local
networks:
  elasticsearch-network:
