name = "api-login"
#type = "javascript"
#account_id = ""
#route = ""
workers_dev = true
compatibility_date = "2022-04-18"

[build]
command = "npm install && npm run build"
#[build.upload]
#format = "service-worker"

[vars]
JWT_KEY = "mySecret"
EMAIL = "henninb@gmail.com"
PASSWORD = "monday1"
