#!/usr/bin/env sh

stack list xmonad-contrib
stack list xmonad
if stack build :xmonad-config; then
  notify-send "xmonad build" "The xmonad build was successful - $1"
else
  notify-send "xmonad build" "The xmonad build had failures"
fi
#stack install :xmonad-config --local-bin-path ~/.local/bin/

install "$(stack exec which xmonad-config)" "$1"

exit 0

# vim: set ft=sh:
