VM_NAME = 'ubuntubox'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1904"
  config.vm.hostname = VM_NAME

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vm.network "public_network", type: "bridge", dev: "br0", mode: "bridge", network_name: "public-network"
  config.vm.provision "file", source: "setup.sh", destination: "~/setup.sh"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
  end

  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c "mkdir -p /home/vagrant/.ssh"
  SHELL
  config.vm.provision "file", source: "/home/henninb/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
end
