#!/bin/sh

export _JAVA_AWT_WM_NONREPARTENTING=1
export LANG="en_US.utf8"
#export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

date >> "$HOME/bspwm.log"

if [ -x "$(command -v dunst)" ]; then
  echo dunst was called. >> "$HOME/bspwm.log"
  exec dunst &
else
  echo dunst is not installed. >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v flameshot)" ]; then
  exec flameshot &
else
  echo "flameshot not installed." >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v blueman-applet)" ]; then
  exec blueman-applet &
else
  echo "blueman-applet not installed." >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v volumeicon)" ]; then
  exec volumeicon &
else
  echo "volumeicon is not installed." >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v feh)" ]; then
  #exec feh --bg-scale --randomize $HOME/backgrounds/* &
  exec feh --bg-scale "$HOME/backgrounds/minnesota-vikings-dark.jpg" &
else
  echo feh is not installed >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v copyq)" ]; then
  echo copyq was called. >> "$HOME/bspwm.log"
  copyq &
else
  echo copyq is not installed. >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v xscreensaver)" ]; then
  exec xscreensaver -no-splash &
else
  echo xscreensaver is not installed >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v sxhkd)" ]; then
  exec sxhkd &
  echo sxhkd was called. >> "$HOME/bspwm.log"
else
  echo sxhkd is not installed >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v polybar)" ]; then
  "$HOME/.config/polybar/launch.sh" bspwm
  echo polybar was called. >> "$HOME/bspwm.log"
else
  echo polybar is not installed >> "$HOME/bspwm.log"
fi

if [ -x "$(command -v wmname)" ]; then
  wmname LG3D >> "$HOME/bspwm.log"
  echo wmname was called. >> "$HOME/bspwm.log"
else
  echo wmname is not installed >> "$HOME/bspwm.log"
fi

#### Polybar ####
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

###---Global Settings---###
#bspc config automatic_scheme alternate
echo top of the config >> "$HOME/bspwm.log"
if ! bspc config initial_polarity second_child; then
  echo bspc config initial_polarity second_child failed. >> "$HOME/bspwm.log"
else
  echo bspc config initial_polarity second_child success. >> "$HOME/bspwm.log"
fi

if ! bspc config pointer_modifier lock; then
  echo bspc config pointer_modifier lock failed. >> "$HOME/bspwm.log"
else
  echo bspc config pointer_modifier lock success. >> "$HOME/bspwm.log"
fi

if ! bspc config pointer_action1 move; then
  echo bspc config pointer_action1 move failed. >> "$HOME/bspwm.log"
else
  echo bspc config pointer_action1 move success. >> "$HOME/bspwm.log"
fi

if ! bspc config pointer_action2 resize_side; then
  echo bspc config pointer_action2 resize_side failed. >> "$HOME/bspwm.log"
else
  echo bspc config pointer_action2 resize_side success. >> "$HOME/bspwm.log"
fi

if ! bspc config pointer_action3 resize_corner; then
  echo bspc config pointer_action3 resize_corner failed. >> "$HOME/bspwm.log"
else
  echo bspc config pointer_action3 resize_corner success. >> "$HOME/bspwm.log"
fi

if ! bspc config click_to_focus none; then
  echo bspc config click_to_focus none failed. >> "$HOME/bspwm.log"
else
  echo bspc config click_to_focus none success. >> "$HOME/bspwm.log"
fi

if ! bspc config focus_follows_pointer true; then
  echo bspc config focus_follows_pointer true failed. >> "$HOME/bspwm.log"
else
  echo bspc config focus_follows_pointer true success. >> "$HOME/bspwm.log"
fi

if ! bspc config remove_disabled_monitors true; then
  echo bspc config remove_disabled_monitors true failed. >> "$HOME/bspwm.log"
else
  echo bspc config remove_disabled_monitors true success. >> "$HOME/bspwm.log"
fi

if ! bspc config remove_unplugged_monitors true; then
  echo bspc config remove_unplugged_monitors failed. >> "$HOME/bspwm.log"
else
  echo bspc config remove_unplugged_monitors success. >> "$HOME/bspwm.log"
fi

if ! bspc config merge_overlapping_monitors true; then
  echo bspc config merge_overlapping_monitors true failed. >> "$HOME/bspwm.log"
else
  echo bspc config merge_overlapping_monitors true success. >> "$HOME/bspwm.log"
fi

if ! bspc config normal_border_color "#4c566a"; then
  echo "bspc config normal_border_color #4c566a failed." >> "$HOME/bspwm.log"
else
  echo "bspc config normal_border_color #4c566a success." >> "$HOME/bspwm.log"
fi

if ! bspc config active_border_color "#1e1e1e"; then
  echo  "bspc config active_border_color #1e1e1e failed." >> "$HOME/bspwm.log"
else
  echo "bspc config active_border_color #1e1e1e success." >> "$HOME/bspwm.log"
fi

if ! bspc config focused_border_color "#406ea5"; then
  echo "bspc config focused_border_color #406ea5 failed." >> "$HOME/bspwm.log"
else
  echo bspc config focused_border_color "#406ea5 success." >> "$HOME/bspwm.log"
fi

if ! bspc config presel_feedback_color "#5e81ac"; then
  echo "bspc config presel_feedback_color #5e81ac failed." >> "$HOME/bspwm.log"
else
  echo "bspc config presel_feedback_color #5e81ac success." >> "$HOME/bspwm.log"
fi

if ! bspc config urgent_border_color "#dd2727"; then
  echo "bspc config urgent_border_color #dd2727 failed." >> "$HOME/bspwm.log"
else
  echo "bspc config urgent_border_color #dd2727 success." >> "$HOME/bspwm.log"
fi

###---Monitor And Desktop Settings----###
if ! bspc config top_padding 27; then
  echo bspc config top_padding 27 failed. >> "$HOME/bspwm.log"
else
  echo bspc config top_padding 27 success. >> "$HOME/bspwm.log"
fi
if ! bspc config bottom_padding 0; then
  echo  bspc config bottom_padding 0 failed. >> "$HOME/bspwm.log"
else
  echo bspc config bottom_padding 0 success. >> "$HOME/bspwm.log"
fi
if ! bspc config left_padding 0; then
  echo  bspc config left_padding 0 failed. >> "$HOME/bspwm.log"
else
  echo bspc config left_padding 0 success. >> "$HOME/bspwm.log"
fi
if ! bspc config right_padding 0; then
  echo  bspc config right_padding 0 failed. >> "$HOME/bspwm.log"
else
  echo bspc config right_padding 0 success. >> "$HOME/bspwm.log"
fi
if ! bspc config border_width 2; then
  echo  bspc config border_width 2 failed. >> "$HOME/bspwm.log"
else
  echo bspc config border_width 2 success. >> "$HOME/bspwm.log"
fi
if ! bspc config window_gap 8; then
  echo  bspc config window_gap 8 failed. >> "$HOME/bspwm.log"
else
  echo bspc config window_gap 8 success. >> "$HOME/bspwm.log"
fi
echo end of the config >> "$HOME/bspwm.log"

###---Rules---###
# bspc rule -a mpv state=fullscreen
# bspc rule -a Zathura state=tiled
# bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

echo monitor setup start >> "$HOME/bspwm.log"
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor rdp0 -d 1 2 3 4 5 6 7 8 9
bspc monitor -d 1 2 3 4 5 6 7 8 9
echo monitor setup end >> "$HOME/bspwm.log"

echo end of script >> "$HOME/bspwm.log"
