#!/bin/sh

export _JAVA_AWT_WM_NONREPARTENTING=1
#export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

#### Autostart ####

date >> $HOME/bspwm.log
if [ -x "$(command -v dunst)" ]; then
  echo dunst was called. >> $HOME/bspwm.log
  dunst &
fi

if [ -x "$(command -v sxhkd)" ]; then
  sxhkd &
  echo sxhkd was called. >> $HOME/bspwm.log
fi

if [ -x "$(command -v polybar)" ]; then
  $HOME/.config/polybar/launch.sh bspwm
  echo polybar was called. >> $HOME/bspwm.log
fi

#### Monitors ####
# bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
# bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
# bspc monitor rdp0 -d 1 2 3 4 5 6 7 8 9

#### Polybar ####
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

###---Global Settings---###
#bspc config automatic_scheme alternate
echo top of the config >> $HOME/bspwm.log
bspc config initial_polarity second_child 2>> $HOME/bspwm.log
echo 01 >> $HOME/bspwm.log
bspc config pointer_modifier lock >> $HOME/bspwm.log
echo 01 >> $HOME/bspwm.log
bspc config pointer_action1 move >> $HOME/bspwm.log
echo 01 >> $HOME/bspwm.log
bspc config pointer_action2 resize_side >> $HOME/bspwm.log
echo 01 >> $HOME/bspwm.log
bspc config pointer_action3 resize_corner >> $HOME/bspwm.log
echo 01 >> $HOME/bspwm.log
bspc config click_to_focus none >> $HOME/bspwm.log
echo 01 >> $HOME/bspwm.log
bspc config focus_follows_pointer true
echo 01 >> $HOME/bspwm.log
bspc config remove_disabled_monitors true
echo 01 >> $HOME/bspwm.log
bspc config remove_unplugged_monitors true
echo 01 >> $HOME/bspwm.log
bspc config merge_overlapping_monitors true
echo 01 >> $HOME/bspwm.log
bspc config normal_border_color "#4c566a"
echo 01 >> $HOME/bspwm.log
bspc config active_border_color "#1e1e1e"
echo 01 >> $HOME/bspwm.log
bspc config focused_border_color "#406ea5"
echo 01 >> $HOME/bspwm.log
bspc config presel_feedback_color "#5e81ac"
echo 01 >> $HOME/bspwm.log
#bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 27
echo 01 2>> $HOME/bspwm.log
bspc config bottom_padding 0
echo 01 2>> $HOME/bspwm.log
bspc config left_padding 0
echo 01 2>> $HOME/bspwm.log
bspc config right_padding 0
echo 01 2>> $HOME/bspwm.log
bspc config border_width 2
echo 01 2>> $HOME/bspwm.log
bspc config window_gap 8
echo end of the config >> $HOME/bspwm.log

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
# bspc rule -a Screenkey manage=off

echo monitor setup >> $HOME/bspwm.log
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor rdp0 -d 1 2 3 4 5 6 7 8 9
bspc monitor -d 1 2 3 4 5 6 7 8 9
echo end of script >> $HOME/bspwm.log
