#!/bin/sh

cat <<  EOF > "$HOME/tmp/70-u2f.rules"
# Copyright (c) 2020 Yubico AB. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#    1. Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#    2. Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# SPDX-License-Identifier: BSD-2-Clause

# This file is automatically generated, and should be used with udev 188
# or newer.

ACTION!="add|change", GOTO="fido_end"

# YubiKey 4 OTP+FIDO+CCID by Yubico AB
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0407", TAG+="uaccess", GROUP="plugdev", MODE="0660"

LABEL="fido_end"
EOF

sudo mv -v "$HOME/tmp/70-u2f.rules" /etc/udev/rules.d/70-u2f.rules
if command -v udevadm; then
  sudo udevadm control --reload-rules
fi
sudo chown root:root /etc/udev/rules.d/70-u2f.rules

sudo emerge --update --newuse libyubikey
sudo emerge --update --newuse app-crypt/yubikey-manager
sudo emerge --update --newuse yubikey-manager-qt
sudo emerge --update --newuse app-crypt/libu2f-server
sudo emerge --update --newuse app-crypt/libu2f-host
sudo emerge --update --newuse sys-auth/pam_u2f
sudo usermod -a -G plugdev "$(whoami)"
sudo emerge --update --newuse sys-fs/mtpfs
# pamu2fcfg -uuser > ~/.config/Yubico/u2f_keys

systemctl status systemd-udevd
echo ykman
echo ykman-gui
ykman list --serials
ykman --device 1234 info

exit 1

git clone https://github.com/Yubico/yubico-c-client.git
cd yubico-c-client
autoreconf --install

git clone https://github.com/Yubico/yubico-pam.git
cd yubico-pam
autoreconf --install
./configure

make check install

exit 0
