version: "3"

services:
  redis-server:
    container_name: redis-server
    hostname: redis-server
    image: bitnami/redis
    ports:
      - "8080:80/tcp"
    environment:
      TZ: 'America/Chicago'
    # volumes:
    #   - './etc-redis:/etc/redis'
    #   - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
