version: "3.7"
services:
  influxdb-server:
    image: influxdb:2.6.0
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: influxdb-server
    hostname: influxdb-server
    # restart: always
    # privileged: true
    volumes:
      - /opt/influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_PASSWORD=monday1
      - INFLUXDB_ADMIN_USER=henninb
      - INFLUXDB_DB=metrics
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    # env_file:
    #   - env.influx
    #   - env.secrets
