version: "3.7"
services:
  apache-server:
    image: httpd:2.4.52
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: apache-server
    ports:
      - "8080:80"
    expose:
      - "8080"
    # volumes:
    #   - ./default.vcl:/default.vcl
